name: Delete ZIP

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Delete ZIP
        run: rm -f aou-mbti-game.zip && git config --global user.email "you@example.com" && git config --global user.name "Your Name" && git add . && git commit -m "Remove zip" && git push || echo "Already deleted"
